task2/task2/Controllers/OrderController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using task2.Models;

namespace task2.Controllers
{
    public class OrderController: Controller
    {
        private readonly AppContext _context;
        
        public OrderController(AppContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize(Roles = "user")]
        public ActionResult MakeOrder()
        {
            var meals = _context.Meals.ToList();
            return View(meals);
        }

        [HttpPost]
        [Authorize(Roles = "user")]
        public async Task<IActionResult> MakeOrder(int[] selectedObjects)
        {
            var order = new Order();
            double total = 0;
            var currentUserEmailClaim = HttpContext.User.Claims.First(c => c.Type == ClaimsIdentity.DefaultNameClaimType);
            var currentUser = _context.Users.First(u => u.Email == currentUserEmailClaim.Value);
            
            foreach (int id in selectedObjects)
            {
                var meal = _context.Meals.First(m => m.Id == id);
                order.Meals.Add(meal);
                total += meal.Price;
            }

            order.UserId = currentUser.Id;
            order.TotalPrice = total;

            
           
            _context.Orders.Add(order);
            return Ok(total);
        }
    }
}

task2/task2/Controllers/RestaurantController.cs
using System.Net;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using task2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace task2.Controllers
{
    public class RestaurantController:Controller
    
    {
        private readonly AppContext _context;
        
        public RestaurantController(AppContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Add()
        {
            if (HttpContext.User.HasClaim(c=>c.Value=="user"))
                ViewData["NavigationForUser"] = true;
            
            return View();
        }
        
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Add(Restaurant model)
        {
            if (HttpContext.User.HasClaim(c=>c.Value=="user"))
                ViewData["NavigationForUser"] = true;
            
            if (ModelState.IsValid)
            {
                var restaurant = new Restaurant();
                restaurant.Name = model.Name;
                _context.Restaurants.Add(restaurant);
                _context.SaveChanges();
//                var currentUserEmailClaim = HttpContext.User.Claims.First(c => c.Type == ClaimsIdentity.DefaultNameClaimType);
//                var currentUser = _context.Users.First(u => u.Email == currentUserEmailClaim.Value);
//                
//                var card = new Card
//                {
//                    PassportSeries = model.PassportSeries,
//                    PassportNumber = model.PassportNumber,
//                    UserId = currentUser.Id,
//                    User = currentUser
//                };
//
//                _context.Cards.Add(card);
//                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Неверные  данные");
            return View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Detail(string id)
        {
            if (HttpContext.User.HasClaim(c=>c.Value=="user"))
                ViewData["NavigationForUser"] = true;

            var restaurant = _context.Restaurants.First(r => r.Id.ToString() == id);
            var meals = _context.Meals.Where(m => m.RestaurantId == restaurant.Id);
            restaurant.Meals = meals.ToList();
               
            return View(restaurant);
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult AddMeal(string id)
        {
            if (HttpContext.User.HasClaim(c=>c.Value=="user"))
                ViewData["NavigationForUser"] = true;
            
            return View();
        }
        
        
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> AddMeal(string id, Meal model)
        {
            if (HttpContext.User.HasClaim(c=>c.Value=="user"))
                ViewData["NavigationForUser"] = true;
            
            if (ModelState.IsValid)
            {
                var meal = new Meal();
                meal.Name = model.Name;
                meal.Price = model.Price;
                meal.RestaurantId = int.Parse(id);
                var rest = _context.Restaurants.First(r => r.Id == meal.RestaurantId);
                meal.Restaurant = rest;
                _context.Meals.Add(meal);
                _context.SaveChanges();
//                var currentUserEmailClaim = HttpContext.User.Claims.First(c => c.Type == ClaimsIdentity.DefaultNameClaimType);
//                var currentUser = _context.Users.First(u => u.Email == currentUserEmailClaim.Value);
//                
//                var card = new Card
//                {
//                    PassportSeries = model.PassportSeries,
//                    PassportNumber = model.PassportNumber,
//                    UserId = currentUser.Id,
//                    User = currentUser
//                };
//
//                _context.Cards.Add(card);
//                _context.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            ModelState.AddModelError("", "Неверные  данные");
            return View(model);
        }
        
    }
}

task2/task2/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using Microsoft.AspNetCore.Http
@{
    bool showForUser = false; // default
    if (ViewData.TryGetValue("NavigationForUser", out var value) && value is bool)
    {
        showForUser = (bool)value;
    }

    var loggedIn = User.Identity.IsAuthenticated;
    

}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - infa</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                 @if (loggedIn && showForUser)
                 {

                         <p>Вы обычный пользователь</p>

                 }
                 else if (loggedIn && !showForUser)
                 {

                         <p>Вы админ</p>

                 }
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">task2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (loggedIn && showForUser)
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="MakeOrder">Make Order</a>
                            </li>

                        }
                        @*                         @if (showForUser) *@
                        @*                         { *@
                        @*                             <li class="nav-item"> *@
                        @*                                 <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="MyProfile">MyProfile</a> *@
                        @*                             </li> *@
                        @*                         } *@
                        
                        @if (loggedIn && !showForUser)
                        {

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Add">Add restaurant</a>
                        </li>

                        }
                        @if (loggedIn)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Sign Out</a>
                            </li>
                        }
                        
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - infa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>